specVersion: 0.0.1
description: Substrate slots auction data collector
repository: git@github.com:subvis-io/subquery-spectator.git
schema: ./schema.graphql
network:
  # endpoint: wss://kusama.api.onfinality.io/public-ws
  endpoint: wss://node-6811272578211844096.sz.onfinality.io/ws?apikey=b2dc23dc-f534-44e8-85dc-5c5676adc10d

dataSources:
  - name: RococoRuntime
    kind: substrate/Runtime
    filter: 
      specName: rococo
    startBlock: 357245
    mapping: 
      handlers: 
      - handler: handleBlock
        kind: substrate/BlockHandler
      - handler: handleEvent
        kind: substrate/EventHandler

  - name: KusamaRuntime
    kind: substrate/Runtime
    filter: 
      specName: kusama
    # startBlock: 7828000
    # first crowdloan registred shortly after
    startBlock: 7828250 
    mapping:
      handlers: 
      - handler: handleBlock
        kind: substrate/BlockHandler
      - handler: handleEvent
        kind: substrate/EventHandler